nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_credentials: true
        allow_headers: ['content-type', 'authorization']
        expose_headers: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
            allow_headers: ['content-type', 'authorization']
            expose_headers: []
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600